version: '4.30'

services:
  # app:
  #   build: /
  #   command: go run .
  #   ports:
  #     - "3000:3000"
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports: 
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
    restart: always
    environment:
       - CASSANDRA_BROADCAST_ADDRESS=host.docker.internal
       - CASSANDRA_SEEDS=host.docker.internal 
    volumes:
        - ./out/cassandra_data:/var/lib/cassandra
    healthcheck:
        test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
        interval: 15s
        timeout: 10s
        retries: 10
  consul:
    image: consul:1.15.4
    container_name: consul
    command: agent -server -bootstrap-expect 1 -ui -bind 0.0.0.0 -advertise=192.168.0.100 -client 0.0.0.0
    ports:
      - 8500:8500
