server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: songs-service
          uri: lb://songs-service
          predicates:
            - Path=/api/v1/**
    consul:
      config:
        enabled: false
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: false
